-- AlterTable
ALTER TABLE "Creator" ADD COLUMN     "circulatingSupply" DOUBLE PRECISION NOT NULL DEFAULT 200000,
ADD COLUMN     "initialPrice" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "liquidity" DOUBLE PRECISION NOT NULL DEFAULT 10000,
ADD COLUMN     "reserveSupply" DOUBLE PRECISION NOT NULL DEFAULT 800000,
ADD COLUMN     "totalSupply" DOUBLE PRECISION NOT NULL DEFAULT 1000000;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isBot" BOOLEAN NOT NULL DEFAULT false;
